CRITICAL - 2024-09-24 06:09:33 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "register.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('register.php')
 2 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('register', [], true)
 3 APPPATH\Controllers\Users.php(9): view('register')
 4 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->index()
 5 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 06:41:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 06:41:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 06:41:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 06:41:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(21): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 06:42:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 06:42:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 06:42:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(21): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 06:42:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 06:43:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 06:43:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fasfads', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'fasfads', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fasfads', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'fasfads', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 06:43:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fasfads', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'fasfads', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(21): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 06:44:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 06:45:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 06:45:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 06:45:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(21): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 06:45:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 06:45:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 14:25:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 14:28:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 14:28:55 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(21): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 14:28:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(21): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 14:28:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 14:34:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-24 14:34:40 --> Error: Call to undefined function ser_value()
in APPPATH\Views\register.php on line 13.
 1 SYSTEMPATH\View\View.php(228): include()
 2 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('register', [], true)
 4 APPPATH\Controllers\Users.php(9): view('register')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 14:35:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-09-24 14:35:27 --> Error: Call to undefined function set_value()
in APPPATH\Views\register.php on line 13.
 1 SYSTEMPATH\View\View.php(228): include()
 2 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('register', [], true)
 4 APPPATH\Controllers\Users.php(9): view('register')
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 14:37:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 14:37:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 14:37:57 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(23): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(23): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 14:37:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(23): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 14:38:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 14:38:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 14:38:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 14:38:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('faddad', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'faddad', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(23): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('faddad', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'faddad', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(23): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 14:38:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('faddad', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'faddad', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(23): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 14:41:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 15:03:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 15:03:39 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('User', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'User', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('User', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'User', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 15:03:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('User', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'User', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(24): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 15:17:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 15:18:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 15:18:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 15:18:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(24): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 15:26:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 15:26:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 15:26:37 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fasdf', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'fasdf', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fasdf', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'fasdf', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 15:26:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fasdf', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'fasdf', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(24): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 15:26:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 15:26:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-09-24 15:28:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-09-24 15:28:03 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'project', 3306, '', 0)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#6 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#7 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using ****: YES) in C:\xampp\htdocs\project\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\project\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\project\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\project\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\project\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\project\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', Array, NULL, 'user')
#5 C:\xampp\htdocs\project\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', Array, Array)
#6 C:\xampp\htdocs\project\system\Controller.php(154): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\project\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\project\system\CodeIgniter.php(943): App\Controllers\Users->create()
#9 C:\xampp\htdocs\project\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#10 C:\xampp\htdocs\project\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\project\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2024-09-24 15:28:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using ****: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `user` = :user:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'user', [...], null, 'user')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('user', 'user', 'Admin', [...], [...])
 6 SYSTEMPATH\Controller.php(154): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\Users.php(24): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Users->create()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2024-09-24 16:03:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
